config/routes.rb
Rails.application.routes.draw do
  resources :games, only: [:index, :create, :show, :update]
  root "games#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game.rb
class Game < ApplicationRecord
  serialize :board, Array

  after_initialize :set_defaults

  def set_defaults
    self.board ||= Array.new(9, " ")
    self.current_player ||= "X"
  end

  def valid_move?(position)
    position.between?(0, 8) && board[position] == " "
  end

  def winner?
    win_combinations = [
      [0, 1, 2], [3, 4, 5], [6, 7, 8], # Rows
      [0, 3, 6], [1, 4, 7], [2, 5, 8], # Columns
      [0, 4, 8], [2, 4, 6]             # Diagonals
    ]

    win_combinations.any? do |combo|
      [board[combo[0]], board[combo[1]], board[combo[2]]].uniq.length == 1 &&
        board[combo[0]] != " "
    end
  end

  def full_board?
    !board.include?(" ")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    if @game.save
      redirect_to @game
    else
      render :new
    end
  end

  def show
    @game = Game.find(params[:id])
  end

  def update
    @game = Game.find(params[:id])
    position = params[:position].to_i
    if @game.valid_move?(position)
      @game.board[position] = @game.current_player
      @game.current_player = @game.current_player == "X" ? "O" : "X"
      @game.save
    end
    redirect_to @game
  end

  private

  def game_params
    params.require(:game).permit(:board, :current_player)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/create.html.erb
<h1>New Game</h1>
<%= form_with model: @game, local: true do |form| %>
  <%= form.submit 'Start Game' %>
<% end %>

app/views/games/index.html.erb
<h1>TicTacToe</h1>
<%= link_to 'New Game', new_game_path %>

app/views/games/show.html.erb
<h1>Game <%= @game.id %></h1>
<div>
  <% @game.board.each_with_index do |cell, index| %>
    <% if (index % 3).zero? %>
      <div style="clear: both;"></div>
    <% end %>
    <div style="float: left; width: 30px; height: 30px; border: 1px solid black; text-align: center;">
      <% if cell == " " %>
        <%= link_to ' ', game_path(@game, position: index), method: :patch %>
      <% else %>
        <%= cell %>
      <% end %>
    </div>
  <% end %>
</div>
<div style="clear: both;"></div>
<% if @game.winner? %>
  <p><%= @game.current_player == "X" ? "O" : "X" %> wins!</p>
<% elsif @game.full_board? %>
  <p>It's a draw!</p>
<% end %>
<%= link_to 'Back to Games', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tictactoe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= javascript_include_tag "application", type: "module" %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>